#!/bin/sh

protected_branch='main'
current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$current_branch" = "$protected_branch" ]; then
    echo "ERROR: Direct push to $protected_branch is not allowed. Please use a feature branch and create a Pull Request."
    exit 1
fi

exit 0
