#!/bin/sh

protected_branch='main'
current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$current_branch" = "$protected_branch" ]; then
    echo "ERROR: Direct commit to $protected_branch is not allowed. Please switch to a feature branch."
    exit 1
fi

exit 0
